[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "20.10.0"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"